ID: aws_elbv2_alb_listener_security
Title: "ELBv2 ALB Listener Security"
Description: "Ensure ELBv2 ALBs are using a secure protocol."
Tags:
    score_service_name:
        - AWS Elastic Load Balancing V2 (ELBv2)
    score_tags:
        - Unencrypted Traffic
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - aws_ec2_application_load_balancer
        - aws_ec2_load_balancer_listener
    Parameters: []
    PrimaryTable: aws_ec2_application_load_balancer
    QueryToExecute: "SELECT \n    al.arn AS resource,\n    al.kaytu_resource_id,\n    al.kaytu_account_id,\n    CASE\n      WHEN STRING_AGG(ll.protocol, ',') ILIKE '%HTTPS%' THEN 'ok'\n      ELSE 'alarm'\n    END AS status,\n    CASE\n      WHEN STRING_AGG(ll.protocol, ',') ILIKE '%HTTPS%' THEN 'alb is using a secure protocol'\n      ELSE 'alb is not using a secure protocol'\n    END AS reason,\n    al.region,\n    al.account_id\nFROM \n    aws_ec2_application_load_balancer al\nLEFT JOIN aws_ec2_load_balancer_listener ll ON al.arn = ll.load_balancer_arn\nGROUP BY \n    al.arn, al.kaytu_resource_id, al.kaytu_account_id, al.title, al.region, al.account_id;\n"
Severity: high
Connector:
    - AWS
