connectors:
- AWS
query: |-
  select
    count(arn) as configuration_count,
    compute_platform
  from
    aws_codedeploy_deployment_config
  group by
    compute_platform;
  
Title: "Steampipe Table: aws_codedeploy_deployment_config - Query AWS CodeDeploy Deployment Configurations using SQL"
Description: "Allows users to query AWS CodeDeploy Deployment Configurations to retrieve information about the deployment configurations within AWS CodeDeploy service."
