Title: "List AWS Serverless Application Repository Applications"
Description: "Allows users to query AWS Serverless Application Repository Applications to fetch details like application name, status, author, description, labels, license URL, creation time, and more."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      author,
      creation_time,
      description
    from
      aws_serverlessapplicationrepository_application;
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Serverless Application Repository
