Title: "List all AWS EC2 Launch Configurations and Metadata"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      iam_instance_profile
    from
      aws_ec2_launch_configuration;
Tags:
  cloud_asset_management: true
  cloud_provider: aws
  cloud_service: EC2
