Title: "Steampipe Table: aws_kinesisanalyticsv2_application - Query AWS Kinesis Analytics Applications using SQL"
Description: "Allows users to query AWS Kinesis Analytics Applications to retrieve detailed information about each application, including the name, ARN, description, status, runtime environment, and more."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          application_name,
          runtime_environment,
          application_arn,
          application_status
        from
          aws_kinesisanalyticsv2_application
        where
          runtime_environment = 'SQL-1_0';
