connectors:
- AWS
query: |-
  select
    region,
    default_ebs_encryption_enabled,
    default_ebs_encryption_key
  from
    aws_ec2_regional_settings
  where
    default_ebs_encryption_enabled;
  
Title: "Steampipe Table: aws_ec2_regional_settings - Query AWS EC2 Regional Settings using SQL"
Description: "Allows users to query AWS EC2 regional settings, including default EBS encryption and default EBS encryption KMS key."
