connectors:
- AWS
query: |-
  select
    name,
    metric_name,
    namespace,
    average,
    maximum,
    minimum,
    sample_count,
    timestamp
  from
    aws_ec2_application_load_balancer_metric_request_count
  order by
    name,
    timestamp;
  
Title: "Steampipe Table: aws_ec2_application_load_balancer_metric_request_count - Query AWS EC2 Application Load Balancer Metrics using SQL"
Description: "Allows users to query AWS EC2 Application Load Balancer Metrics, specifically the request count."
