connectors:
- AWS
query: |-
  select
    arn,
    deployment_group_id,
    deployment_group_name,
    application_name,
    deployment_style,
    region
  from
    aws_codedeploy_deployment_group;
  
Title: "Steampipe Table: aws_codedeploy_deployment_group - Query AWS CodeDeploy Deployment Groups using SQL"
Description: "Allows users to query AWS CodeDeploy Deployment Group details including deployment configurations, target revisions, and associated alarm configurations."
