connectors:
- AWS
query: |-
  select
    name,
    cloud_watch_encryption ->> 'CloudWatchEncryptionMode' as encyption_mode,
    cloud_watch_encryption ->> 'KmsKeyArn' as kms_key_arn
  from
    aws_glue_security_configuration
  where
    cloud_watch_encryption ->> 'CloudWatchEncryptionMode' != 'DISABLED';
  
Title: "Steampipe Table: aws_glue_security_configuration - Query AWS Glue Security Configurations using SQL"
Description: "Allows users to query AWS Glue Security Configurations and gain insights into the security configurations of Glue resources."
