Title: "Steampipe Table: aws_ec2_application_load_balancer_metric_request_count - Query AWS EC2 Application Load Balancer Metrics using SQL"
Description: "Allows users to query AWS EC2 Application Load Balancer Metrics, specifically the request count."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          name,
          metric_name,
          namespace,
          maximum,
          minimum,
          average
          sample_count,
          timestamp
        from
          aws_ec2_application_load_balancer_metric_request_count
        where
          average < 100
        order by
          name,
          timestamp;
