Title: "Find daily request count metrics of AWS EC2 ALB"
Description: "Allows users to query daily request count metrics of the AWS EC2 Application Load Balancer."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      metric_name,
      namespace,
      average,
      maximum,
      minimum,
      sample_count,
      timestamp
    from
      aws_ec2_application_load_balancer_metric_request_count_daily
    order by
      name,
      timestamp;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: EC2 Application Load Balancer
