connectors:
- AWS
query: |-
  select
    name,
    iam_instance_profile
  from
    aws_ec2_launch_configuration;
  
Title: "Steampipe Table: aws_ec2_launch_configuration - Query AWS EC2 Launch Configurations using SQL"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
