Title: "Steampipe Table: aws_sagemaker_endpoint_configuration - Query AWS SageMaker Endpoint Configurations using SQL"
Description: "Allows users to query AWS SageMaker Endpoint Configurations to retrieve detailed information about each endpoint configuration in the AWS SageMaker service."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          name,
          arn,
          kms_key_id,
          creation_time,
          production_variants,
          tags
        from
          aws_sagemaker_endpoint_configuration;
