Title: "Steampipe Table: aws_config_aggregate_authorization - Query AWS Config Aggregate Authorizations using SQL"
Description: "Allows users to query AWS Config Aggregate Authorizations, providing vital information about AWS Config rules and their respective authorizations in an aggregated form."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          arn,
          authorized_account_id,
          authorized_aws_region,
          creation_time
        from
          aws_config_aggregate_authorization;
