connectors:
- AWS
query: |-
  select
    name,
    creation_date_time,
    encryption_configuration,
    instance_metadata_service_configuration,
    security_configuration
  from
    aws_emr_security_configuration;
  
Title: "Steampipe Table: aws_emr_security_configuration - Query AWS EMR Security Configurations using SQL"
Description: "Allows users to query AWS EMR (Amazon Elastic MapReduce) Security Configurations. This table provides information about security settings and configurations that can be applied to EMR clusters, managing encryption, authentication, and authorization. These configurations are crucial for ensuring the secure handling of data, protecting sensitive information, and complying with various data security standards and regulations."
