connectors:
- AWS
query: |-
  select
    name,
    arn,
    author,
    creation_time,
    description
  from
    aws_serverlessapplicationrepository_application;
  
Title: "Steampipe Table: aws_serverlessapplicationrepository_application - Query AWS Serverless Application Repository Applications using SQL"
Description: "Allows users to query AWS Serverless Application Repository Applications to fetch details like application name, status, author, description, labels, license URL, creation time, and more."
