connectors:
- AWS
query: |-
  select
    registry_id,
    region
  from
    aws_ecr_registry_scanning_configuration
  where
    scanning_configuration ->> 'ScanType' = 'ENHANCED'
  
Title: "Steampipe Table: aws_ecr_registry_scanning_configuration - Query AWS ECR Registry Scanning Configuration using SQL"
Description: "Allows users to query AWS ECR Registry Scanning Configuration at the private registry level on a per-region basis."
