Title: "Find AWS EMR Block Public Access Configuration Details"
Description: "Allows users to query AWS EMR Block Public Access Configuration to retrieve details about the block public access configurations for EMR clusters."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      created_by_arn,
      block_public_security_group_rules,
      creation_date,
      classification,
      permitted_public_security_group_rule_ranges
    from
      aws_emr_block_public_access_configuration
    order by
      created_by_arn,
      creation_date;
Tags:
  cloud_network_security: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: EMR
