connectors:
- AWS
query: |-
  select
    name,
    rule_id,
    arn,
    rule_state,
    created_by,
    scope
  from
    aws_config_rule;
  
Title: "Steampipe Table: aws_config_rule - Query AWS Config Rules using SQL"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
