connectors:
- AWS
query: |-
  select
    name,
    arn,
    cluster_name,
    type
  from
    aws_eks_identity_provider_config
  where 
    type = 'oidc';
  
Title: "Steampipe Table: aws_eks_identity_provider_config - Query Amazon EKS Identity Provider Configurations using SQL"
Description: "Allows users to query Amazon EKS Identity Provider Configurations for detailed information about the identity provider configurations for Amazon EKS clusters."
