Title: "Steampipe Table: aws_route53_resolver_query_log_config - Query AWS Route 53 Resolver Query Log Config using SQL"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          name,
          id,
          creator_request_id,
          destination_arn
        from
          aws_route53_resolver_query_log_config
        where
          status = 'FAILED';
