connectors:
- AWS
query: |-
  select
    arn,
    deployment_config_id,
    deployment_config_name,
    compute_platform,
    create_time,
    region
  from
    aws_codedeploy_deployment_config;
  
Title: "Steampipe Table: aws_codedeploy_deployment_config - Query AWS CodeDeploy Deployment Configurations using SQL"
Description: "Allows users to query AWS CodeDeploy Deployment Configurations to retrieve information about the deployment configurations within AWS CodeDeploy service."
