Title: "Steampipe Table: aws_config_rule - Query AWS Config Rules using SQL"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          name,
          rule_id,
          tags
        from
          aws_config_rule
        where
          name Like '%s3-bucket%';
