Title: "List all details of AWS Elastic Beanstalk Versions"
Description: "Allows users to query AWS Elastic Beanstalk Application Versions to obtain details about their configurations, environments, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      application_name,
      application_version_arn,
      version_label,
      date_updated
    from
      aws_elastic_beanstalk_application_version
    order by
      date_updated desc;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: Elastic Beanstalk
