connectors:
- AWS
query: |-
  select
    arn,
    id,
    name,
    description,
    tags
  from
    aws_appconfig_application;
  
Title: "Steampipe Table: aws_appconfig_application - Query AWS AppConfig Applications using SQL"
Description: "Allows users to query AWS AppConfig Applications to gather detailed information about each application, including its name, description, associated environments, and more."
