connectors:
- AWS
query: |-
  select
    name,
    created_time_stamp,
    cloud_watch_encryption,
    job_bookmarks_encryption,
    s3_encryption
  from
    aws_glue_security_configuration;
  
Title: "Steampipe Table: aws_glue_security_configuration - Query AWS Glue Security Configurations using SQL"
Description: "Allows users to query AWS Glue Security Configurations and gain insights into the security configurations of Glue resources."
