connectors:
- AWS
query: |-
  select
    name,
    conformance_pack_id,
    delivery_s3_bucket,
    delivery_s3_key_prefix
  from
    aws_config_conformance_pack;
  
Title: "Steampipe Table: aws_config_conformance_pack - Query AWS Config Conformance Packs using SQL"
Description: "Allows users to query AWS Config Conformance Packs to fetch information about the AWS Config conformance packs deployed on an AWS account."
