connectors:
- AWS
query: |-
  select
    created_by_arn,
    block_public_security_group_rules,
    creation_date,
    classification,
    permitted_public_security_group_rule_ranges
  from
    aws_emr_block_public_access_configuration
  order by
    created_by_arn,
    creation_date;
  
Title: "Steampipe Table: aws_emr_block_public_access_configuration - Query AWS EMR Block Public Access Configuration using SQL"
Description: "Allows users to query AWS EMR Block Public Access Configuration to retrieve details about the block public access configurations for EMR clusters."
