connectors:
- AWS
query: |-
  select
    name,
    arn,
    description,
    date_created,
    date_updated,
    versions
  from
    aws_elastic_beanstalk_application;
  
Title: "Steampipe Table: aws_elastic_beanstalk_application - Query AWS Elastic Beanstalk Applications using SQL"
Description: "Allows users to query AWS Elastic Beanstalk Applications to obtain details about their configurations, versions, environment, and other metadata."
