connectors:
- AWS
query: |-
  select
    name,
    retention_period_in_days,
    title,
    region
  from
    aws_config_retention_configuration
  where
    region = 'us-east-1';
  
Title: "Steampipe Table: aws_config_retention_configuration - Query AWS Config Retention Configuration using SQL"
Description: "Allows users to query AWS Config Retention Configuration for information about the retention period that AWS Config uses to retain your configuration items."
