connectors:
- AWS
query: |-
  select
    name,
    metric_name,
    namespace,
    maximum,
    minimum,
    average
    sample_count,
    timestamp
  from
    aws_ec2_application_load_balancer_metric_request_count_daily
  where
    average < 100
  order by
    name,
    timestamp;
  
Title: "Steampipe Table: aws_ec2_application_load_balancer_metric_request_count_daily - Query AWS EC2 Application Load Balancer using SQL"
Description: "Allows users to query daily request count metrics of the AWS EC2 Application Load Balancer."
