Title: "Find AWS EC2 Launch Configurations and Security Groups"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      jsonb_array_elements_text(security_groups) as security_groups
    from
      aws_ec2_launch_configuration;
Tags:
  cloud_asset_management: true
  cloud_provider: aws
  cloud_service: EC2
