connectors:
- AWS
query: |-
  select
    name,
    user_data
  from
    aws_ec2_launch_configuration
  where
    user_data like any (array ['%pass%', '%secret%','%token%','%key%'])
    or user_data ~ '(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]';
  
Title: "Steampipe Table: aws_ec2_launch_configuration - Query AWS EC2 Launch Configurations using SQL"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
