connectors:
- AWS
query: |-
  select
    application_name,
    application_version_arn,
    version_label,
    date_updated
  from
    aws_elastic_beanstalk_application_version
  order by
    date_updated desc;
  
Title: 
Description: "Allows users to query AWS Elastic Beanstalk Application Versions to obtain details about their configurations, environments, and other metadata."
