Title: "Steampipe Table: aws_eks_identity_provider_config - Query Amazon EKS Identity Provider Configurations using SQL"
Description: "Allows users to query Amazon EKS Identity Provider Configurations for detailed information about the identity provider configurations for Amazon EKS clusters."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: "select\n  name,\n  arn,\n  cluster_name,\n  type\nfrom\n  aws_eks_identity_provider_config\nwhere \n  type = 'oidc';"
