connectors:
- AWS
query: |-
  select
    encryption_at_rest,
    connection_password_encryption,
    region,
    account_id
  from
    aws_glue_data_catalog_encryption_settings;
  
Title: "Steampipe Table: aws_glue_data_catalog_encryption_settings - Query AWS Glue Data Catalog using SQL"
Description: "Allows users to query AWS Glue Data Catalog Encryption Settings."
