connectors:
- AWS
query: |-
  select
    name,
    id,
    creation_time,
    destination_arn,
    status
  from
    aws_route53_resolver_query_log_config
  where
    creation_time >= now() - interval '30' day;
  
Title: "Steampipe Table: aws_route53_resolver_query_log_config - Query AWS Route 53 Resolver Query Log Config using SQL"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
