connectors:
- AWS
query: |-
  select
    name as config_rule_name,
    c ->> 'Mode' as evaluation_mode
  from
    aws_config_rule,
    jsonb_array_elements(evaluation_modes) as c
  where
    c ->> 'Mode' = 'PROACTIVE';
  
Title: "Steampipe Table: aws_config_rule - Query AWS Config Rules using SQL"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
