Title: "List all AWS Config Conformance Packs"
Description: "Allows users to query AWS Config Conformance Packs to fetch information about the AWS Config conformance packs deployed on an AWS account."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      conformance_pack_id,
      created_by,
      last_update_requested_time,
      title,
      akas
    from
      aws_config_conformance_pack;
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - AWS Config
