connectors:
- AWS
query: |-
  select
    name,
    application_id,
    application_aggregated_status ->> 'HealthStatus' as health_status,
    application_aggregated_status ->> 'ProgressStatus' as progress_status,
    application_aggregated_status ->> 'TotalSourceServers' as total_source_servers
  from
    aws_mgn_application;
  
Title: "Steampipe Table: aws_mgn_application - Query AWS Migration Service Applications using SQL"
Description: "Allows users to query AWS Migration Service Applications to retrieve detailed information about each application."
