connectors:
- AWS
query: |-
  select
    name,
    count(az ->> 'ZoneName') < 2 as zone_count_1
  from
    aws_ec2_application_load_balancer
    cross join jsonb_array_elements(availability_zones) as az
  group by
    name;
  
Title: "Steampipe Table: aws_ec2_application_load_balancer - Query AWS EC2 Application Load Balancer using SQL"
Description: "Allows users to query AWS EC2 Application Load Balancer, providing detailed information about each load balancer within an AWS account. This includes its current state, availability zones, security groups, and other important attributes."
