Title: "List all AWS CodeDeploy Deployment Configurations"
Description: "Allows users to query AWS CodeDeploy Deployment Configurations to retrieve information about the deployment configurations within AWS CodeDeploy service."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      count(arn) as configuration_count,
      compute_platform
    from
      aws_codedeploy_deployment_config
    group by
      compute_platform;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: CodeDeploy
