Title: "Find AWS Elastic Beanstalk Application Details"
Description: "Allows users to query AWS Elastic Beanstalk Applications to obtain details about their configurations, versions, environment, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      description,
      date_created,
      date_updated,
      versions
    from
      aws_elastic_beanstalk_application;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: Elastic Beanstalk
