Title: "Find AWS Glue Security Configurations with Encryption"
Description: "Allows users to query AWS Glue Security Configurations and gain insights into the security configurations of Glue resources."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      cloud_watch_encryption ->> 'CloudWatchEncryptionMode' as encyption_mode,
      cloud_watch_encryption ->> 'KmsKeyArn' as kms_key_arn
    from
      aws_glue_security_configuration
    where
      cloud_watch_encryption ->> 'CloudWatchEncryptionMode' != 'DISABLED';
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Glue Security
