Title: "Steampipe Table: aws_ecr_registry_scanning_configuration - Query AWS ECR Registry Scanning Configuration using SQL"
Description: "Allows users to query AWS ECR Registry Scanning Configuration at the private registry level on a per-region basis."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          registry_id,
          region
        from
          aws_ecr_registry_scanning_configuration
        where
          scanning_configuration ->> 'ScanType' = 'ENHANCED'
