Title: "List AWS Serverless App Repo Applications by Verified Author"
Description: "Allows users to query AWS Serverless Application Repository Applications to fetch details like application name, status, author, description, labels, license URL, creation time, and more."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      author,
      is_verified_author
    from
      aws_serverlessapplicationrepository_application
    where
      is_verified_author;
Tags:
  cloud_identity_security:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Serverless Application Repository
