connectors:
- AWS
query: |-
  select
    registry_id,
    jsonb_pretty(scanning_configuration),
    region
  from
    aws_ecr_registry_scanning_configuration
  where
    region = 'ap-south-1';
  
Title: "Steampipe Table: aws_ecr_registry_scanning_configuration - Query AWS ECR Registry Scanning Configuration using SQL"
Description: "Allows users to query AWS ECR Registry Scanning Configuration at the private registry level on a per-region basis."
