connectors:
- AWS
query: |-
  select
    name,
    application_id,
    creation_date_time,
    is_archived,
    wave_id
  from
    aws_mgn_application
  where
    creation_date_time >= now() - interval '30' day;
  
Title: "Steampipe Table: aws_mgn_application - Query AWS Migration Service Applications using SQL"
Description: "Allows users to query AWS Migration Service Applications to retrieve detailed information about each application."
