connectors:
- AWS
query: |-
  select
    created_by_arn,
    creation_date
  from
    aws_emr_block_public_access_configuration
  where
    date_part('day', now() - creation_date) < 90;
  
Title: "Steampipe Table: aws_emr_block_public_access_configuration - Query AWS EMR Block Public Access Configuration using SQL"
Description: "Allows users to query AWS EMR Block Public Access Configuration to retrieve details about the block public access configurations for EMR clusters."
