Title: "Steampipe Table: aws_ec2_launch_configuration - Query AWS EC2 Launch Configurations using SQL"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
Connectors:
    - AWS
Query:
    Engine: odysseus-v0.0.1
    QueryToExecute: |-
        select
          name,
          created_time,
          associate_public_ip_address,
          ebs_optimized,
          image_id,
          instance_monitoring_enabled,
          instance_type,
          key_name
        from
          aws_ec2_launch_configuration;
