Title: "List AWS Migration Service Applications with Details"
Description: "Allows users to query AWS Migration Service Applications to retrieve detailed information about each application."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      application_id,
      creation_date_time,
      is_archived
    from
      aws_mgn_application
    where
      is_archived;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: AWS Migration Service
