Title: "Find all AWS Elastic Beanstalk Environments' Health Status"
Description: "Allows users to query AWS Elastic Beanstalk Environments to gain insights into their configuration, status, health, related applications, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      environment_name,
      health_status
    from
      aws_elastic_beanstalk_environment
    where
      health_status = 'Suspended';
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Elastic Beanstalk
