Title: "Find Amazon EKS Identity Providers' Configurations"
Description: "Allows users to query Amazon EKS Identity Provider Configurations for detailed information about the identity provider configurations for Amazon EKS clusters."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      arn,
      cluster_name,
      tags,
      status
    from
      aws_eks_identity_provider_config;
Tags:
  cloud_identity_security: true
  cloud_provider: aws
  cloud_service: Amazon EKS
