connectors:
- AWS
query: |-
  select
    name,
    id,
    arn,
    creation_time,
    share_status,
    status
  from
    aws_route53_resolver_query_log_config;
  
Title: "Steampipe Table: aws_route53_resolver_query_log_config - Query AWS Route 53 Resolver Query Log Config using SQL"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
