Title: "Find AWS Config Rules with Inactive Rule State"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      rule_id,
      arn,
      rule_state
    from
      aws_config_rule
    where
      rule_state <> 'ACTIVE';
Tags:
  cloud_asset_management:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Config
