Title: "Find AWS CodeDeploy Deployment Group Details including Alarms"
Description: "Allows users to query AWS CodeDeploy Deployment Group details including deployment configurations, target revisions, and associated alarm configurations."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn,
      deployment_group_id,
      deployment_group_name,
      auto_rollback_configuration ->> 'Enabled' as auto_rollback_configuration_enabled
    from
      aws_codedeploy_deployment_group
    where
      auto_rollback_configuration ->> 'Enabled' = 'true';
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: CodeDeploy
