Title: "List all Intelligent Tiering Configurations in AWS S3"
Description: "Allows users to query Intelligent Tiering configurations for S3 buckets. It provides information about each configuration, including the bucket name, the ID of the configuration, and the status of the configuration."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      bucket_name,
      id,
      status,
      tierings
    from
      aws_s3_bucket_intelligent_tiering_configuration;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: S3 Bucket
