Title: "List All AWS EC2 Regions With Encryption Settings"
Description: "Allows users to query AWS EC2 regional settings, including default EBS encryption and default EBS encryption KMS key."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      region,
      default_ebs_encryption_enabled,
      default_ebs_encryption_key
    from
      aws_ec2_regional_settings
    where
      default_ebs_encryption_enabled;
Tags:
  cloud_data_security: true
  cloud_provider: aws
  cloud_service: EC2
