Title: "List all AWS Elastic Beanstalk Environment Details"
Description: "Allows users to query AWS Elastic Beanstalk Environments to gain insights into their configuration, status, health, related applications, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      environment_id,
      environment_name,
      application_name,
      arn,
      tier
    from
      aws_elastic_beanstalk_environment;
Tags:
  cloud_ops: true
  cloud_provider: aws
  cloud_service: Elastic Beanstalk
