Title: "Find AWS EC2 Launch Configurations With Sensitive Data"
Description: "Allows users to query AWS EC2 Launch Configurations to gain insights into their configurations, metadata, and associated instances."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: "select\n  name,\n  user_data\nfrom\n  aws_ec2_launch_configuration\nwhere\n  user_data like any (array ['%pass%', '%secret%','%token%','%key%'])\n  or user_data ~ '(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]';"
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - EC2
