Title: "Find AWS Elastic Beanstalk Environments and Operations"
Description: "Allows users to query AWS Elastic Beanstalk Environments to gain insights into their configuration, status, health, related applications, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      environment_name,
      abortable_operation_in_progress
    from
      aws_elastic_beanstalk_environment
    where
      abortable_operation_in_progress = 'true';
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Elastic Beanstalk
