Title: "Find AWS CodeDeploy Deployment Groups with Alarm Configs"
Description: "Allows users to query AWS CodeDeploy Deployment Group details including deployment configurations, target revisions, and associated alarm configurations."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn,
      deployment_group_id,
      deployment_group_name,
      alarm_configuration ->> 'Enabled' as alarm_configuration_enabled
    from
      aws_codedeploy_deployment_group
    where
      alarm_configuration ->> 'Enabled' = 'true';
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - CodeDeploy
