Title: "List all AWS Elastic Beanstalk Application Versions Details"
Description: "Allows users to query AWS Elastic Beanstalk Application Versions to obtain details about their configurations, environments, and other metadata."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      application_name,
      application_version_arn,
      version_label
    from
      aws_elastic_beanstalk_application_version
    where
      source_build_information ->> 'SourceRepository' = 'CodeCommit';
Tags:
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Elastic Beanstalk
