Title: "List AWS CodeDeploy Deployment Configs and Details"
Description: "Allows users to query AWS CodeDeploy Deployment Configurations to retrieve information about the deployment configurations within AWS CodeDeploy service."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn,
      deployment_config_id,
      deployment_config_name,
      compute_platform,
      create_time,
      region
    from
      aws_codedeploy_deployment_config;
Tags:
  cloud_asset_management:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - CodeDeploy
