Title: "Find AWS AppConfig Application Details"
Description: "Allows users to query AWS AppConfig Applications to gather detailed information about each application, including its name, description, associated environments, and more."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn,
      id,
      name,
      description,
      tags
    from
      aws_appconfig_application;
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - AppConfig
