Title: "Find AWS Route 53 Resolver Query Log Configurations"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      id,
      share_status,
      association_count
    from
      aws_route53_resolver_query_log_config
    where
      share_status = 'SHARED';
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Route 53
