ID: aws_all_controls_config
Title: Config
SectionCode: config
Description: This section contains recommendations for configuring Config resources.
Children: []
Tags: {}
Enabled: true
AutoAssign: false
Controls:
- aws_config_configuration_recorder_no_failed_deliver_logs
- aws_config_enabled_all_regions
