ID: azure_rbi_itf_nbfc_v2017_it_information_and_cyber_security
Title: Information and Cyber Security
SectionCode: it_information_and_cyber_security
Description: ""
Children:
- azure_rbi_itf_nbfc_v2017_it_information_and_cyber_security_3
Tags: {}
Enabled: true
AutoAssign: false
Controls: []
