ID: azure_all_controls_automation
Title: Automation
SectionCode: automation
Description: This section contains recommendations for configuring Automation resources.
Children: []
Tags: {}
Enabled: true
AutoAssign: false
Controls:
- azure_automation_account_variable_encryption_enabled
