ID: azure_all_controls_appconfiguration
Title: App Configuration
SectionCode: appconfiguration
Description: This section contains recommendations for configuring App Configuration resources.
Children: []
Tags: {}
Enabled: true
AutoAssign: false
Controls:
- azure_app_configuration_encryption_enabled
- azure_app_configuration_private_link_used
- azure_app_configuration_sku_standard
