ID: aws_ec2_instance_no_iam_role_with_write_permission_on_critical_s3_configuration
Title: EC2 instance IAM role should not allow write permission on critical s3 configuration
Description: This control ensures that EC2 instance IAM roles do not allow write permission on critical s3 configuration.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      i.arn as resource,
      i.kaytu_account_id as kaytu_account_id,
      i.kaytu_resource_id as kaytu_resource_id,
      case
        when p.arn is null then 'ok'
        else 'alarm'
      end status,
      case
        when p.arn is null then title || ' has no IAM role with write permission on critical s3 configuration.'
        else title || ' has IAM role with write permission on critical s3 configuration.'
      end as reason
    from
      aws_ec2_instance as i
      left join iam_roles as r on r.intance_arn = i.arn
      left join iam_role_with_permission as p on p.arn = r.role_arn;
  PrimaryTable: aws_ec2_instance
  ListOfTables:
  - aws_ec2_instance
  - iam_roles
  - iam_role_with_permission
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
