ID: aws_lambda_function_dead_letter_queue_configured
Title: Lambda functions should be configured with a dead-letter queue
Description: Enable this rule to help notify the appropriate personnel through AWS Simple Queue Service (AWS SQS) or AWS Simple Notification Service (AWS SNS) when a function has failed.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
        select
          arn as resource,
          case
            when dead_letter_config_target_arn is null then 'alarm'
            else 'ok'
          end as status,
          case
            when dead_letter_config_target_arn is null then title || ' configured with dead-letter queue.'
            else title || ' not configured with dead-letter queue.'
          end as reason
          
          
        from
          aws_lambda_function;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
