ID: azure_securitycenter_notify_alerts_configured
Title: Ensure that 'Notify about alerts with the following severity' is set to 'High'
Description: Enables emailing security alerts to the subscription owner or other designated security contact.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    with contact_info as (
      select
        count(*) filter (where alert_notifications = 'On') as notification_alert_count,
        subscription_id
      from
        azure_security_center_contact
      group by
        subscription_id
      limit 1
    )
    select
      sub.subscription_id as resource,
      sub.kaytu_account_id as kaytu_account_id,
      sub.kaytu_resource_id as kaytu_resource_id,
      case
        when notification_alert_count > 0 then 'ok'
        else 'alarm'
      end as status,
      case
        when notification_alert_count > 0 then '"Notify about alerts with the following severity" set to High.'
        else '"Notify about alerts with the following severity" not set to High.'
      end as reason
      
      , sub.display_name as subscription
    from
      azure_subscription sub
      left join contact_info ci on sub.subscription_id = ci.subscription_id;
  Connector:
  - Azure
  PrimaryTable: azure_security_center_contact
  ListOfTables:
  - azure_security_center_contact
  - azure_subscription
  Parameters: []
  Global: false
ManualVerification: false
Severity: low
Tags:
  category:
  - Compliance
  cis:
  - "true"
  cis_item_id:
  - "2.14"
  cis_level:
  - "1"
  cis_section_id:
  - "2"
  cis_type:
  - automated
  cis_version:
  - v1.3.0
  plugin:
  - azure
  service:
  - Azure/SecurityCenter
Managed: false
