ID: azure_securitycenter_notify_alerts_configured
Title: "Ensure that 'Notify about alerts with the following severity' is set to 'High'"
Description: "Enables emailing security alerts to the subscription owner or other designated security contact."
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - azure_security_center_contact
        - azure_subscription
    Parameters: []
    PrimaryTable: azure_security_center_contact
    QueryToExecute: "with contact_info as (\n  select\n    count(*) filter (where alert_notifications = 'On') as notification_alert_count,\n    subscription_id\n  from\n    azure_security_center_contact\n  group by\n    subscription_id\n  limit 1\n)\nselect\n  sub.subscription_id as resource,\n  sub.kaytu_account_id as kaytu_account_id,\n  sub.kaytu_resource_id as kaytu_resource_id,\n  case\n    when notification_alert_count > 0 then 'ok'\n    else 'alarm'\n  end as status,\n  case\n    when notification_alert_count > 0 then '\"Notify about alerts with the following severity\" set to High.'\n    else '\"Notify about alerts with the following severity\" not set to High.'\n  end as reason\n  \n  , sub.display_name as subscription\nfrom\n  azure_subscription sub\n  left join contact_info ci on sub.subscription_id = ci.subscription_id;\n"
Severity: low
Tags:
    category:
        - Compliance
    cis:
        - "true"
    cis_item_id:
        - "2.14"
    cis_level:
        - "1"
    cis_section_id:
        - "2"
    cis_type:
        - automated
    cis_version:
        - v1.3.0
    plugin:
        - azure
    service:
        - Azure/SecurityCenter
Connector:
    - Azure
