ID: azure_compute_vm_container_security_configurations_vulnerabilities_remediated
Title: Vulnerabilities in container security configurations should be remediated
Description: Audit vulnerabilities in security configuration on machines with Docker installed and display as recommendations in Azure Security Center.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
        select
          id as resource,
          'info' as status,
          'Manual verification required.' as reason,
          display_name as subscription
        from
          azure_subscription;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- azure
Tags: {}
Severity: low
