ID: aws_foundational_security_config
Title: Config
SectionCode: config
Description: ""
Children: []
Tags:
  aws_foundational_security:
  - "true"
  category:
  - Compliance
  plugin:
  - aws
  service:
  - AWS/Config
  type:
  - Benchmark
Enabled: true
AutoAssign: false
Controls:
- aws_foundational_security_config_1
