ID: azure_hipaa_hitrust_v92_portable_media_security
Title: 03 Portable Media Security
SectionCode: portable_media_security
Description: The organization, based on the data classification level, registers media (including laptops) prior to use, places reasonable restrictions on how such media be used, and provides an appropriate level of physical and logical protection (including encryption) for media containing covered information until properly destroyed or sanitized.
Children:
- azure_hipaa_hitrust_v92_0301_09o1organizational
- azure_hipaa_hitrust_v92_0302_09o2organizational
- azure_hipaa_hitrust_v92_0304_09o3organizational
Tags:
  category:
  - Compliance
  hipaa_hitrust_v92:
  - "true"
  plugin:
  - azure
  service:
  - Azure
  type:
  - Benchmark
Enabled: true
AutoAssign: false
Controls: []
