ID: aws_baseline_security
Title: "Security for AWS"
Description: "Comprehensive security controls and benchmarks for AWS environments, categorized for streamlined management."
AutoAssign: true
Children:
  - aws_baseline_security_iam
  - aws_baseline_security_network
  - aws_baseline_security_data_protection
  - aws_baseline_security_monitoring
  - aws_baseline_security_infrastructure
Controls: []
Enabled: false
SectionCode: aws_baseline_security
Tags:
  baseline_category:
    - security
  type:
    - BASELINE
TracksDriftEvents: false

