ID: azure_baseline_security
Title: "Security for Azure"
Description: "Comprehensive security controls and benchmarks for Azure environments, categorized for streamlined management."
AutoAssign: true
Children:
  - azure_baseline_security_iam
  - azure_baseline_security_network
  - azure_baseline_security_data_protection
  - azure_baseline_security_monitoring
  - azure_baseline_security_infrastructure
Controls: []
Enabled: true
SectionCode: azure_baseline_security
Tags:
  baseline_category:
    - security
  type:
    - BASELINE
TracksDriftEvents: false

