ID: aws_dms_endpoint_ssl_configured
Title: DMS endpoints should use SSL
Description: This control checks whether an AWS DMS endpoint uses an SSL connection. The control fails if the endpoint doesn't use SSL.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
        select
          arn as resource,
          case
            when ssl_mode = 'none' then 'alarm'
            else 'ok'
          end as status,
          case
            when ssl_mode = 'none' then title || ' SSL not configured.'
            else title || ' SSL configured.'
          end as reason
          
          
        from
          aws_dms_endpoint;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
