ID: aws_api_gatewayv2_route_authorizer_configured
Title: API Gateway V2 authorizer should be configured
Description: This control checks whether API Gateway V2 has an authorizer configured. This rule is non-compliant if API Gateway V2 has no authorizers configured.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
        select
          'arn:' || partition || ':apigateway:' || region || '::/apis/' || api_id || '/routes/' || route_id as resource,
          case
            when authorizer_id is null then 'alarm'
            else 'ok'
          end as status,
          case
            when authorizer_id is null then route_id || ' authorizer not configured.'
            else route_id || ' authorizer ' || authorizer_id || ' configured.'
          end as reason
          
        from
          aws_api_gatewayv2_route;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
