ID: aws_unrestricted_security_group_ingress_on_uncommon_ports
Title: "Unrestricted Security Group Ingress on Uncommon Ports"
Description: "Ensure no security group contains any 0.0.0.0/0 ingress rules."
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - aws_vpc_security_group
    Parameters: []
    PrimaryTable: aws_vpc_security_group
    QueryToExecute: "SELECT \n  group_name as resource,\n  kaytu_resource_id,\n  kaytu_account_id,\n  CASE\n    WHEN exists (\n      select 1\n      from jsonb_array_elements(ip_permissions) as p,\n      jsonb_array_elements(p -> 'IpRanges') as r\n      where ((p ->> 'IpRanges') LIKE '%0.0.0.0/0%' or (p ->> 'IpRanges' LIKE '%::/0%'))\n    ) THEN 'alarm'\n    ELSE 'ok'\n  END AS status,\n  CASE\n    WHEN exists (\n      select 1\n      from jsonb_array_elements(ip_permissions) as p,\n      jsonb_array_elements(p -> 'IpRanges') as r\n      where ((p ->> 'IpRanges') LIKE '%0.0.0.0/0%' or (p ->> 'IpRanges' LIKE '%::/0%'))\n    ) THEN group_name || ' has Unrestricted Access' \n    ELSE group_name || ' Access is secure'\n  END AS reason,\n  region,\n  account_id\nFROM \n  aws_vpc_security_group\n"
Severity: medium
Tags:
    score_service_name:
        - AWS EC2
    score_tags:
        - Exposed Endpoints
Connector:
    - AWS
