ID: 26
Query:
  ID: azure_insight_compute_availability_set_without_managed_disk_configuration
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      sku_name, subscription_id, kaytu_account_id, kaytu_resource_id
    from
      azure_compute_availability_set
    where
      sku_name = 'Classic';
  Connector:
  - Azure
  PrimaryTable: azure_compute_availability_set
  ListOfTables:
  - azure_compute_availability_set
  Parameters: []
Connector: Azure
ShortTitle: AV Sets with Legacy Disks
LongTitle: List of availability sets which does not use managed disks configuration
Description: List of availability sets which does not use managed disks configuration
LogoURL: ""
Tags:
  category:
  - Security
  - Technical Debt
  - Resiliency
  - Cost Management
Links: []
Enabled: true
Internal: false
