ID: 37
Query:
  ID: azure_insight_legacy_application_gateway
  Engine: odysseus-v0.0.1
  QueryToExecute: SELECT name, id, sku->'tier' AS tier, subscription_id, kaytu_account_id, kaytu_resource_id FROM azure_application_gateway WHERE NOT sku IS NULL AND sku->>'tier' = 'Standard_v2';
  Connector:
  - Azure
  PrimaryTable: azure_application_gateway
  ListOfTables:
  - azure_application_gateway
  Parameters: []
Connector: Azure
ShortTitle: Legacy Application Gateways
LongTitle: Legacy Application Gateways
Description: This insight returns all legacy application gateways.
LogoURL: ""
Tags:
  category:
  - Technical Debt
  persona:
  - Executive
  - Product
  - FinOps
Links: []
Enabled: true
Internal: false
