ID: azure_application_gateway_waf_uses_specified_mode
Title: Web Application Firewall (WAF) should use the specified mode for Application Gateway
Description: Mandates the use of 'Detection' or 'Prevention' mode to be active on all Web Application Firewall policies for Application Gateway.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    ```sql
    select
      ag.id as resource,
      ag.kaytu_account_id as kaytu_account_id,
      ag.kaytu_resource_id as kaytu_resource_id,
      case
        when (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') in ('Prevention','Detection') then 'ok'
        else 'alarm'
      end as status,
      case
        when (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') in ('Prevention','Detection') then ag.name || ' WAF mode is set to ' || (web_application_firewall_configuration::json -> 'PolicySettings' ->> 'mode') || '.'
        else ag.name || ' WAF mode is not set to Prevention or Detection mode.' 
      end as reason
    from
      azure_application_gateway as ag
      join azure_subscription as sub on sub.subscription_id = ag.subscription_id;
    ```
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- azure
Tags: {}
Severity: low
